// LIST
export const GET_LIST_MOVIES_REQUEST = 'GET_LIST_MOVIES_REQUEST';
export const GET_LIST_MOVIES_SUCCESS = 'GET_LIST_MOVIES_SUCCESS';
export const GET_LIST_MOVIES_FAILURE = 'GET_LIST_MOVIES_FAILURE';
